<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Huella extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Huella_model');
    } 

    /*
     * Listing of huellas
     */
    function index()
    {
        $data['huellas'] = $this->Huella_model->get_all_huellas();
        
        $data['_view'] = 'huella/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new huella
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'DESAPARECIDOSidDes' => $this->input->post('DESAPARECIDOSidDes'),
				'imagen' => $this->input->post('imagen'),
            );
            
            $huella_id = $this->Huella_model->add_huella($params);
            redirect('huella/index');
        }
        else
        {
			$this->load->model('Desaparecido_model');
			$data['all_desaparecidos'] = $this->Desaparecido_model->get_all_desaparecidos();
            
            $data['_view'] = 'huella/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a huella
     */
    function edit($idHuella)
    {   
        // check if the huella exists before trying to edit it
        $data['huella'] = $this->Huella_model->get_huella($idHuella);
        
        if(isset($data['huella']['idHuella']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'DESAPARECIDOSidDes' => $this->input->post('DESAPARECIDOSidDes'),
					'imagen' => $this->input->post('imagen'),
                );

                $this->Huella_model->update_huella($idHuella,$params);            
                redirect('huella/index');
            }
            else
            {
				$this->load->model('Desaparecido_model');
				$data['all_desaparecidos'] = $this->Desaparecido_model->get_all_desaparecidos();

                $data['_view'] = 'huella/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The huella you are trying to edit does not exist.');
    } 

    /*
     * Deleting huella
     */
    function remove($idHuella)
    {
        $huella = $this->Huella_model->get_huella($idHuella);

        // check if the huella exists before trying to delete it
        if(isset($huella['idHuella']))
        {
            $this->Huella_model->delete_huella($idHuella);
            redirect('huella/index');
        }
        else
            show_error('The huella you are trying to delete does not exist.');
    }
    
}
