<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reconocimiento extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Reconocimiento_model');
    } 

    /*
     * Listing of reconocimiento
     */
    function index()
    {
        $data['reconocimiento'] = $this->Reconocimiento_model->get_all_reconocimiento();
        
        $data['_view'] = 'reconocimiento/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new reconocimiento
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'DESAPARECIDOSidDes' => $this->input->post('DESAPARECIDOSidDes'),
				'imagen' => $this->input->post('imagen'),
				'patron' => $this->input->post('patron'),
				'json' => $this->input->post('json'),
            );
            
            $reconocimiento_id = $this->Reconocimiento_model->add_reconocimiento($params);
            redirect('reconocimiento/index');
        }
        else
        {
			$this->load->model('Desaparecido_model');
			$data['all_desaparecidos'] = $this->Desaparecido_model->get_all_desaparecidos();
            
            $data['_view'] = 'reconocimiento/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a reconocimiento
     */
    function edit($idRec)
    {   
        // check if the reconocimiento exists before trying to edit it
        $data['reconocimiento'] = $this->Reconocimiento_model->get_reconocimiento($idRec);
        
        if(isset($data['reconocimiento']['idRec']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'DESAPARECIDOSidDes' => $this->input->post('DESAPARECIDOSidDes'),
					'imagen' => $this->input->post('imagen'),
					'patron' => $this->input->post('patron'),
					'json' => $this->input->post('json'),
                );

                $this->Reconocimiento_model->update_reconocimiento($idRec,$params);            
                redirect('reconocimiento/index');
            }
            else
            {
				$this->load->model('Desaparecido_model');
				$data['all_desaparecidos'] = $this->Desaparecido_model->get_all_desaparecidos();

                $data['_view'] = 'reconocimiento/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The reconocimiento you are trying to edit does not exist.');
    } 

    /*
     * Deleting reconocimiento
     */
    function remove($idRec)
    {
        $reconocimiento = $this->Reconocimiento_model->get_reconocimiento($idRec);

        // check if the reconocimiento exists before trying to delete it
        if(isset($reconocimiento['idRec']))
        {
            $this->Reconocimiento_model->delete_reconocimiento($idRec);
            redirect('reconocimiento/index');
        }
        else
            show_error('The reconocimiento you are trying to delete does not exist.');
    }
    
}
