<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tutorium extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tutorium_model');
    } 

    /*
     * Listing of tutoria
     */
    function index()
    {
        $data['tutoria'] = $this->Tutorium_model->get_all_tutoria();
        
        $data['_view'] = 'tutorium/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tutorium
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'PERSONAidPersona' => $this->input->post('PERSONAidPersona'),
				'DESAPARECIDOSidDes' => $this->input->post('DESAPARECIDOSidDes'),
				'parentesco' => $this->input->post('parentesco'),
            );
            
            $tutorium_id = $this->Tutorium_model->add_tutorium($params);
            redirect('tutorium/index');
        }
        else
        {
			$this->load->model('Persona_model');
			$data['all_persona'] = $this->Persona_model->get_all_persona();

			$this->load->model('Desaparecido_model');
			$data['all_desaparecidos'] = $this->Desaparecido_model->get_all_desaparecidos();
            
            $data['_view'] = 'tutorium/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tutorium
     */
    function edit($idTutoria)
    {   
        // check if the tutorium exists before trying to edit it
        $data['tutorium'] = $this->Tutorium_model->get_tutorium($idTutoria);
        
        if(isset($data['tutorium']['idTutoria']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'PERSONAidPersona' => $this->input->post('PERSONAidPersona'),
					'DESAPARECIDOSidDes' => $this->input->post('DESAPARECIDOSidDes'),
					'parentesco' => $this->input->post('parentesco'),
                );

                $this->Tutorium_model->update_tutorium($idTutoria,$params);            
                redirect('tutorium/index');
            }
            else
            {
				$this->load->model('Persona_model');
				$data['all_persona'] = $this->Persona_model->get_all_persona();

				$this->load->model('Desaparecido_model');
				$data['all_desaparecidos'] = $this->Desaparecido_model->get_all_desaparecidos();

                $data['_view'] = 'tutorium/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tutorium you are trying to edit does not exist.');
    } 

    /*
     * Deleting tutorium
     */
    function remove($idTutoria)
    {
        $tutorium = $this->Tutorium_model->get_tutorium($idTutoria);

        // check if the tutorium exists before trying to delete it
        if(isset($tutorium['idTutoria']))
        {
            $this->Tutorium_model->delete_tutorium($idTutoria);
            redirect('tutorium/index');
        }
        else
            show_error('The tutorium you are trying to delete does not exist.');
    }
    
}
