<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Desaparecido_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get desaparecido by idDes
     */
    function get_desaparecido($idDes)
    {
        return $this->db->get_where('desaparecidos',array('idDes'=>$idDes))->row_array();
    }
        
    /*
     * Get all desaparecidos
     */
    function get_all_desaparecidos()
    {
        $this->db->order_by('idDes', 'desc');
        return $this->db->get('desaparecidos')->result_array();
    }
        
    /*
     * function to add new desaparecido
     */
    function add_desaparecido($params)
    {
        $this->db->insert('desaparecidos',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update desaparecido
     */
    function update_desaparecido($idDes,$params)
    {
        $this->db->where('idDes',$idDes);
        return $this->db->update('desaparecidos',$params);
    }
    
    /*
     * function to delete desaparecido
     */
    function delete_desaparecido($idDes)
    {
        return $this->db->delete('desaparecidos',array('idDes'=>$idDes));
    }
}
