<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Huella_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get huella by idHuella
     */
    function get_huella($idHuella)
    {
        return $this->db->get_where('huellas',array('idHuella'=>$idHuella))->row_array();
    }
        
    /*
     * Get all huellas
     */
    function get_all_huellas()
    {
        $this->db->order_by('idHuella', 'desc');
        return $this->db->get('huellas')->result_array();
    }
        
    /*
     * function to add new huella
     */
    function add_huella($params)
    {
        $this->db->insert('huellas',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update huella
     */
    function update_huella($idHuella,$params)
    {
        $this->db->where('idHuella',$idHuella);
        return $this->db->update('huellas',$params);
    }
    
    /*
     * function to delete huella
     */
    function delete_huella($idHuella)
    {
        return $this->db->delete('huellas',array('idHuella'=>$idHuella));
    }
}
