<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Publicacion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get publicacion by idPubli
     */
    function get_publicacion($idPubli)
    {
        return $this->db->get_where('publicacion',array('idPubli'=>$idPubli))->row_array();
    }
        
    /*
     * Get all publicacion
     */
    function get_all_publicacion()
    {
        $this->db->order_by('idPubli', 'desc');
        return $this->db->get('publicacion')->result_array();
    }
        
    /*
     * function to add new publicacion
     */
    function add_publicacion($params)
    {
        $this->db->insert('publicacion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update publicacion
     */
    function update_publicacion($idPubli,$params)
    {
        $this->db->where('idPubli',$idPubli);
        return $this->db->update('publicacion',$params);
    }
    
    /*
     * function to delete publicacion
     */
    function delete_publicacion($idPubli)
    {
        return $this->db->delete('publicacion',array('idPubli'=>$idPubli));
    }
}
