<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reconocimiento_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get reconocimiento by idRec
     */
    function get_reconocimiento($idRec)
    {
        return $this->db->get_where('reconocimiento',array('idRec'=>$idRec))->row_array();
    }
        
    /*
     * Get all reconocimiento
     */
    function get_all_reconocimiento()
    {
        $this->db->order_by('idRec', 'desc');
        return $this->db->get('reconocimiento')->result_array();
    }
        
    /*
     * function to add new reconocimiento
     */
    function add_reconocimiento($params)
    {
        $this->db->insert('reconocimiento',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update reconocimiento
     */
    function update_reconocimiento($idRec,$params)
    {
        $this->db->where('idRec',$idRec);
        return $this->db->update('reconocimiento',$params);
    }
    
    /*
     * function to delete reconocimiento
     */
    function delete_reconocimiento($idRec)
    {
        return $this->db->delete('reconocimiento',array('idRec'=>$idRec));
    }
}
