<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tutorium_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tutorium by idTutoria
     */
    function get_tutorium($idTutoria)
    {
        return $this->db->get_where('tutoria',array('idTutoria'=>$idTutoria))->row_array();
    }
        
    /*
     * Get all tutoria
     */
    function get_all_tutoria()
    {
        $this->db->order_by('idTutoria', 'desc');
        return $this->db->get('tutoria')->result_array();
    }
        
    /*
     * function to add new tutorium
     */
    function add_tutorium($params)
    {
        $this->db->insert('tutoria',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tutorium
     */
    function update_tutorium($idTutoria,$params)
    {
        $this->db->where('idTutoria',$idTutoria);
        return $this->db->update('tutoria',$params);
    }
    
    /*
     * function to delete tutorium
     */
    function delete_tutorium($idTutoria)
    {
        return $this->db->delete('tutoria',array('idTutoria'=>$idTutoria));
    }
}
